news_source:
  cryptorank: "https://api.cryptorank.io/v0/news"

interval_config:
  sentiment_delay: 6
  fetch_delay: 10
  miner_delay: 15

news_config:
  limit: 200
  start_timestamp: 1600300000000
  increment_timestamp: 100000000

miner_config:
  scraping_limit: 100

sentiment_config:
  sentiment_limit: 100