# database config
database:
  # database dev config
  dev:
    host:
    port: 
    username:
    password:
    dbname:
# end database config

# news source
news_source:
  cryptorank: "https://api.cryptorank.io/v0/news"
# end news source

# news config
news_config:
  limit: 200
# end news config
